### ISSUE TITLE
unable to compile/run fanuc-driver

### ISSUE THREAD

**Issue by sdrshnptl** [Ladder99/fanuc-driver#115]
System Raspberry pi aarch64

[log.txt](https://github.com/user-attachments/files/17174468/log.txt)

```bash
$ "$fanuc_driver_folder/fanuc/bin/Debug/net7.0/linux-arm64/publish/fanuc" --nlog "/home/sdrshnptl/fanuc-driver/examples/docker/nlog.config" --config "/home/sdrshnptl/fanuc-driver/examples/docker/config.system.yml,/home/sdrshnptl/fanuc-driver/examples/docker/config.user.yml,/home/sdrshnptl/fanuc-driver/examples/docker/config.machines.yml"
.
.
.
.
.
.


         at l99.driver.base.Machines.RunAsync(CancellationToken stoppingToken) in /home/sdrshnptl/fanuc-driver/base-driver/base/Machines.cs:line 80
         at l99.driver.fanuc.FanucService.ExecuteAsync(CancellationToken stoppingToken) in /home/sdrshnptl/fanuc-driver/fanuc/Program.cs:line 48
         at Microsoft.Extensions.Hosting.Internal.Host.TryExecuteBackgroundServiceAsync(BackgroundService backgroundService)
info: Microsoft.Hosting.Lifetime[0]
      Application is shutting down...
```

**Comment by MRIIOT** [comment]
Linux builds have not been tested for a while.  We have primarily focused on Docker releases.
