### ISSUE TITLE
Is it possible to use MQTT over websockets?

### ISSUE THREAD

**Issue by tukusejssirs** [Ladder99/fanuc-driver#24]
I recently refactored a portion of our app to use MQTT for other stuff too, but I need to use websockets, as the clients (all by the one created by `fanuc-driver`) are created on the frontend side.

I suspect that I could change `net_ip` to `ws://localhost` in `config.yaml`, but would that work?

Also I need to uniquely identify the client created by `fanuc-driver`, as no other client should be able to publish messages (only the broker and the client create by `fanuc-driver` should be able to publish messages). Is there a way to do that? Does `fanuc-driver` add something specific? Or the only option is to allow publishing based on the topic names?

Anyway, currently I cannot access the Fanucs, therefore I can test it next week only.

**Update:**

Based on the [docs (Broker tab)](https://docs.ladder99.com/en/drivers/base-driver#configuration), I see I can use use authentication (`user` and `password`) which might solve my issue with allowing only the `fanuc-driver` MQTT client to publish messages.

**Comment by tukusejssirs** [comment]
> No, will need to add WS client support. https://github.com/Ladder99/base-driver/blob/c129ffc36e99204debd91017436c018f73db6c5e/base/mqtt/Broker.cs#L60

I tried to change that like to `.WithWebSocketServer(cfg.ip + ':' + cfg.port)`, but it raises an error and dumps core. It seems like that is much more work to do besides adding a simple configuration option.

```js
Unhandled exception. System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.                          
 ---> Microsoft.CSharp.RuntimeBinder.RuntimeBinderException: Cannot perform runtime binding on a null reference                                      
   at CallSite.Target(Closure , CallSite , Object , String )
   at System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 arg1)                                                  
   at l99.driver.fanuc.FanucMachine..ctor(Machines machines, Boolean enabled, String id, Object config) in /root/fanuc/fanuc-driver/fanuc/FanucMachine.cs:line 45
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)         
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)              
   at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture)                             
   at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   at System.Activator.CreateInstance(Type type, Object[] args)
   at System.Dynamic.UpdateDelegates.UpdateAndExecute3[T0,T1,T2,TRet](CallSite site, T0 arg0, T1 arg1, T2 arg2)                                      
   at l99.driver.base.Machines.Add(Object cfg, Broker broker) in /root/fanuc/fanuc-driver/base-driver/base/Machines.cs:line 57                       
   at System.Dynamic.UpdateDelegates.UpdateAndExecute3[T0,T1,T2,TRet](CallSite site, T0 arg0, T1 arg1, T2 arg2)                                      
   at l99.driver.base.Machines.CreateMachines(Object config) in /root/fanuc/fanuc-driver/base-driver/base/Machines.cs:line 161                       
   at CallSite.Target(Closure , CallSite , Object )
   at System.Dynamic.UpdateDelegates.UpdateAndExecute1[T0,TRet](CallSite site, T0 arg0)                                                              
   at l99.driver.fanuc.Program.Main(String[] args) in /root/fanuc/fanuc-driver/fanuc/Program.cs:line 11                                              
   at l99.driver.fanuc.Program.<Main>(String[] args)
Aborted (core dumped)
```

**Comment by MRIIOT** [comment]
WS support added.  No WSS yet.

https://github.com/Ladder99/fanuc-driver/blob/f9cb5bc9273e10613f940cd6e2e895ee45c56991/fanuc/config-example.yml#L32-L42

**Comment by MRIIOT** [comment]
TLS can be added in the future if demand calls for it.
